export  const backendUrl = `https://mazibai.herokuapp.com/`
// export  const backendUrl = `http://localhost:5000/`
export  const authLoginUrl = `${backendUrl}api/auth/user/login`
export  const authRegisterUrl  = `${backendUrl}api/auth/user/register`
export  const googleLogin = `${backendUrl}api/auth/user/googlelogin`  
export  const loginUserDetails = `${backendUrl}api/user/getuserinfo`
export  const userEdit = `${backendUrl}api/auth/user/edit`
export  const bookNowUrl = `${backendUrl}api/bookings/book`
export  const bookEdit  = `${backendUrl}api/bookings/edit/`
export  const allBookings = `${backendUrl}api/bookings/userbookings`
export  const notificationUrl = `${backendUrl}api/notifications/getuser` 
export  const addNotificationUrl = `${backendUrl}api/notifications/add/`
export  const deleteNotificationUrl = `${backendUrl}api/notifications/delete/`
export  const imageUpload = `${backendUrl}api/upload/user`
export  const wantJob = `${backendUrl}api/job/wantjob`
export  const ReferMaidUrl = `${backendUrl}api/maidrefer/refer`
export  const PartnerUrl = `${backendUrl}api/partner/collab`
export  const getReviews = `${backendUrl}api/reviews/getall`
